MAINTAINERS

docs: Add maintainers

---

README.md
bindings.h
cli/main.go
libuast.go

Added some improvements to the README aswell, but there's still lots to do there.

Update to current libuast API

---

.travis.yml
Makefile
bindings.h
client.go
libuast.go
parse_request.go
parse_request_test.go

Add support to build libuast directly

---

.travis.yml
README.md
_example/main.go
doc.go

*: Prepare v2

---

Makefile

libuast: Bump to 1.2.0

---

README.md

docs: Add a query to the README example and link to guide.

---

Makefile
tools/bindings.h
tools/filter.go

libuast: Bump to 1.4.0 and improve error handling

---

Makefile

libuast: Bump to 1.4.1

---

.travis.yml
README.md

Fixes #30 
Signed-off-by: Juanjo Alvarez <juanjo@sourced.tech>

Add note to readme about innocuous failure after `go get`

---

.travis.yml
Makefile
README.md
tools/bindings.go
tools/bindings.h
tools/filter_test.go
tools/iterator_test.go

Signed-off-by: Juanjo Alvarez <juanjo@sourced.tech>

Added libuast's iterators.

---

tools/bindings.go

Fixes: https://github.com/bblfsh/client-go/issues/37

make it compilable on mac os

---

Makefile
tools/bindings.go
tools/iterator_test.go

Fixes #46.
Signed-off-by: Juanjo Alvarez <juanjo@sourced.tech>

Add support for position iterator

---

request.go

Signed-off-by: Santiago M. Mola <santi@mola.io>

fix request ReadFile on Windows

---

client.go
client_test.go
request.go

Required by https://github.com/bblfsh/sdk/issues/253
Blocked by ~https://github.com/bblfsh/sdk/pull/259~ and ~https://github.com/bblfsh/bblfshd/pull/167~
Blocks https://github.com/bblfsh/dashboard/pull/133
(see https://github.com/bblfsh/sdk/pull/259 description)

client-go. Add SupportedLanguages method

---

Makefile

Currently `make dependencies` doesn't work on MacOS.

Fix Makefile on MacOS

---

README.md

Fix flag in docs

---

tools/bindings.go
tools/filter_test.go

Differentiate invalid expression error in Filter

---

cmd/bblfsh-cli/main.go

This should be useful for anyone trying to give bblfsh a try from the command line.
Will it appear as a binary directly on the release, @smola?

create bblfsh-cli command

---

request.go

Expose UAST mode for v2 requests

---

Gopkg.lock
Gopkg.toml

Switch to a latest sdk v2 version

---

README.md

Signed-off-by: Maartje Eyskens <maartje@sourced.tech>

Fix dead getting started link

---

Gopkg.lock

Update SDK and XPath library

---

cmd/bblfsh-cli/main.go

Show help message once in CLI

---

README.md

doc: add bblfsh-cli to the readme

---

Gopkg.lock
request.go

Use mode parse function from SDK

---

.travis.yml
Gopkg.lock
Gopkg.toml
client.go
cmd/bblfsh-cli/main.go
request.go
request_test.go

See https://github.com/bblfsh/sdk/pull/321 for the definition of error codes.
Requires https://github.com/bblfsh/sdk/pull/321
Resolves #82 

Support error codes

---

Gopkg.lock
Gopkg.toml

Update SDK version

---

.travis.yml

Refactor CI config as per @bzz suggestion. See [this thread](https://github.com/bblfsh/go-client/pull/118#discussion_r274843648) for details.

Refactor CI config
